### ISSUE TITLE
[Feature Request] add an abc2xml.js script

### ISSUE THREAD

**Issue by zaun** [seisiuneer/abctools#9]
Would love an abc2xml.js that does the opposite of xml2abc.js so its is possible to go back and forth between the 2 formats.

**Comment by seisiuneer** [comment]
I wish there were such a thing too, but sadly there is not.On Apr 7, 2024, at 9:25 PM, Justin ***@***.***> wrote:﻿
Would love an abc2xml.js that does the opposite of xml2abc.js so its is possible to go back and forth between the 2 formats.

**Comment by seisiuneer** [comment]
@zaun  I've added the ability to export your ABC in MusicXML format just by specifying .xml as the file extension when you save a file.

The ABC to MusicXML conversion is being done using Willem Vree's abc2xml Python tool that I've converted to a web service and am hosting as a Flask application at pythonanywhere.com

Because of how abc2xml works, the ABC to MusicXML conversion is limited to the first tune in the ABC editor area so if you need to convert an entire tunebook from ABC to MusicXML, you will need to do it one tune at a time.

The resulting MusicXML files can be opened back in the tool.

Demo video:

https://youtu.be/EuhJAjDv6GQ

**Comment by seisiuneer** [comment]
@zaun 
Change of plans on how to do MusicXML export from my ABC Transcription Tools.

I've decided to consolidate the MusicXML export under the "Export All Tunes" dialog.

Now there is a new "Export All Tunes as MusicXML" button on the "More Tools"/"Export All Tunes" dialog (only available on desktop browsers).

When clicked, each ABC tune in the editor will be exported to its own MusicXML file with the same name as the tune.
This works the same way for one tune or a hundred.

The ABC to MusicXML conversion is being done using Willem Vree's abc2xml Python tool that I've converted to a web service and am hosting as a Flask application at pythonanywhere.com

The first pass implementation where you would just save the ABC with a .xml extension had limitations and has been removed in favor of this more robust method.

Please use the new "Export All Tunes as MusicXML" feature on the "More Tools"/"Export All Tunes" dialog going forward.

Demo video
[https://www.youtube.com/watch?v=ecxJQHD4FMQ](https://www.youtube.com/watch?v=ecxJQHD4FMQ)
